### ISSUE TITLE
hilbish install fails when trying to import keys using AUR

### ISSUE THREAD

**Issue by Joshument** [Rosettea/Hilbish#115]
When attempting to install hilbish using paru v1.9.3 (henceforth the AUR as well), installation fails when I attempt to import the gpg key for lua-succulent-git-r7.96dc95c-1 (`098F50DFBCEEC71A4EAB6DA450EE40A2809851F5`) and instead prompts me with this instead: 
`gpg: keyserver receive failed: No data
error: failed to run: gpg --recv-keys 098F50DFBCEEC71A4EAB6DA450EE40A2809851F5:`
attempting to install the hilbish-git version also reveals that the hilbish-git-1.0.4-r3.g0113a4e-1 gpg key `784DF7A14968C5094E16839C904FC49417B44DCD` has the same issue. Testing it on my laptop which is running yay also has the same results.

To reproduce, attempt to install the package from the AUR using any AUR package manager. You should get the same error, or I am just a massive goof and screwing something up terribly.

**Comment by TorchedSammy** [comment]
@lmartinez-mirror

**Comment by lmartinez-mirror** [comment]
@Joshument You have to import @TorchedSammy's keys directly from GitHub, they are not distributed on any keyserver.

`curl https://github.com/torchedsammy.gpg` should download the keys; I'll have to clarify that in the PKGBUILD.

**Comment by TorchedSammy** [comment]
oh, I might be able to upload it to opepgp keyserver in a few hours

**Comment by Joshument** [comment]
> @Joshument You have to import @TorchedSammy's keys directly from GitHub, they are not distributed on any keyserver.
> 
> `curl https://github.com/torchedsammy.gpg` should download the keys; I'll have to clarify that in the PKGBUILD.

I see, thank you! Hopefully that saves me from building from source directly.

**Comment by Joshument** [comment]
just imported the gpg key via the link I was given, however the issue for lua-succulent-git-r7.96dc95c-1 still persists. It appears as if the link I received was only for hilbish-git

**Comment by lmartinez-mirror** [comment]
I don't even remember how I got that key... I'll have to get back to you on that.

**Comment by mateodd25** [comment]
I am having the same issue. Any idea where can I get the key?

**Comment by ccoint** [comment]
Same issue for me too.

**Comment by lmartinez-mirror** [comment]
As I cannot find the keys for the succulent repo, I will temporarily remove the validpgpkeys array from `lua-succulent-git`. I'm aware this is terrible practice in Arch, but I could not for the life of me find the old keys. It would be best if @TorchedSammy used their new key set in succulent the next time they push any changes.
