### ISSUE TITLE
retriving a previous command places the cursor at the end of the 2nd last character instead of the 1st

### ISSUE THREAD

**Issue by Joshument** [Rosettea/Hilbish#121]
Title is fairly self explanatory

To recreate the issue, open any terminal emulator with the hilbish shell, enter a command, and retrieve it (afaik the only way to do so is using the up / down keys. I think I heard about vi bindings but I've never used them so)

**Comment by Joshument** [comment]
![image](https://user-images.githubusercontent.com/74075169/159199554-d7468ea6-bb1e-4339-b61d-33adf023fba0.png)
image example

**Comment by TorchedSammy** [comment]
noticed this with personal usage, thanks go readline lib
