### ISSUE TITLE
golua panic: Cannot compile r2

### ISSUE THREAD

**Issue by willeccles** [Rosettea/Hilbish#142]
## Description
Panics immediately at startup with latest master build. I've attached the full stack trace, but the initial panic message is this:

```
panic: Cannot compile r2 := Op(257)(r1, r4): invalid op [recovered]
        panic: Cannot compile r2 := Op(257)(r1, r4): invalid op
```

### System info:
- Hilbish v1.2.0-48-g1e48a3e
- Void Linux in WSL2
- Go 1.18.1

[hilbish_panic_log.txt](https://github.com/Rosettea/Hilbish/files/8514173/hilbish_panic_log.txt)

**Comment by TorchedSammy** [comment]
this only happens when compiled with go 1.18 (works normally with 1.17.9), just waiting for a respond from golua
