### ISSUE TITLE
hilbish-git installed from AUR does not include many builtin commands

### ISSUE THREAD

**Issue by Joshument** [Rosettea/Hilbish#149]
When installing Hilbish from the AUR,  it appears as if both the `guide` command and `cd` command do not work. I'm not sure which other ones don't work but I think cd especially is important

**Comment by TorchedSammy** [comment]
this is due to a change of the prelude (again),
it got renamed and reorganized

**Comment by TorchedSammy** [comment]
https://github.com/Rosettea/Hilbish/commit/9e596dc271d18b7f8be9b07c7bce2028357857d2 specifically

**Comment by TorchedSammy** [comment]
cc @lmartinez-mirror

**Comment by lmartinez-mirror** [comment]
Thanks for bringing this to my attention. I'll be pushing a fix soon.
