### ISSUE TITLE
hilbish.prompt: %d character isn't autorefreshing when go to another directory

### ISSUE THREAD

**Issue by AlphaTechnolog** [Rosettea/Hilbish#175]
so if i use the next config:

```lua
local hilbish = require "hilbish"

hilbish.prompt('%d ')
```

it works, and it shows me the prompt correctly:

`~ `

but if i go to `~/.config` using `cd`, it don't autorefresh:

```sh
~ cd ~/.config
~ echo it keeps the ~
```

**Comment by TorchedSammy** [comment]
this would just be a matter of hilbish always setting the prompt with the line reader, and i think it makes sense

**Comment by AlphaTechnolog** [comment]
> this would just be a matter of hilbish always setting the prompt with the line reader, and i think it makes sense

yep, but this is the right way to do this? or exists another better way? or i'm doing something wrong?

**Comment by TorchedSammy** [comment]
> yep, but this is the right way to do this?

yes

**Comment by AlphaTechnolog** [comment]
oh ok

**Comment by AlphaTechnolog** [comment]
so, why is this opened? i solved this problem catching that event

**Comment by TorchedSammy** [comment]
hilbish itself should auto refresh prompt to not need the hook for basic prompts like that (i mentioned that in my opening comment0

**Comment by AlphaTechnolog** [comment]
oh ok, cool

**Comment by TorchedSammy** [comment]
actually i'll keep it to how it currently is
