### ISSUE TITLE
[ISSUE] I can't install with task

### ISSUE THREAD

**Issue by linuxmobile** [Rosettea/Hilbish#191]
Hi. I want to install it with task but anything happen.

Go and task is already installed

https://i.imgur.com/oJqnOb2.png

and 

https://i.imgur.com/fqFD76o.png

I follow the steps by isn't working.

**Comment by TorchedSammy** [comment]
uh, you installed the wrong task

**Comment by TorchedSammy** [comment]
the package is go-task in the aur. either use that or do an install via the script on the website

**Comment by linuxmobile** [comment]
> the package is go-task in the aur. either use that or do an install via the script on the website

Oh... that's why! Thx a lot. Amazing work with it
