### ISSUE TITLE
get stdout of hilbish.run

### ISSUE THREAD

**Issue by AlphaTechnolog** [Rosettea/Hilbish#196]
Hello! :wave:

I'm trying to make support to the git branch in my prompt, but i tried using hilbish.run and trying to get the stdout and don't works :c

here is my code:

```lua
local function get_git_branch()
    local status, stdout, stderr = hilbish.run('git branch', true)

    if stdout ~= "" then
        return stdout
    end

    return nil
end
```

but that function always returns nil, and print the stdout in the terminal without catching it in my variable, here is the demonstration:

![Screenshot from 2022-08-12 12-27-54](https://user-images.githubusercontent.com/54639968/184402493-e836d0c7-5f63-4a82-905b-81a701460a1b.png)

Idk if i'm doing smth wrong, please tell me if i'm doing something wrong lol

**Comment by TorchedSammy** [comment]
you are using the function correctly and it also works on my end. you have to be using at least commit 0fc5f457adf1c8d8b8fefc94ab9d940cacb275b6 for stdout/stderr returns

**Comment by TorchedSammy** [comment]
and for this usage specifically, [here is how delta does it](https://github.com/TorchedSammy/Delta/blob/c0d04cfba16f381637358d4d029460ea8d24dbe7/delta.lua#L18), which is my own prompt

**Comment by AlphaTechnolog** [comment]
ah lol, well now i tried with this code, and seems that it's working more: (based in delta xd)

```lua
local hilbish = require 'hilbish'

local function branch ()
    local _, gitbranch = hilbish.run('git rev-parse --abbrev-ref HEAD', false)

    return gitbranch:gsub('\n', '')
end

print(branch())
```

![Screenshot from 2022-08-12 19-28-06](https://user-images.githubusercontent.com/54639968/184456595-b4909f02-e6ee-4c76-b857-2bd239750f05.png)

but i don't really know how to remove that 1 (that changes to 0 when the command fails), do you know how can i remove it?

**Comment by AlphaTechnolog** [comment]
if i remove `gitbranch:gsub('\n', '')`, it hide the number, but when i remove it, it doesn't trim the last line space, but if i add it (the string.gsub), for some reason, it adds the 0 or the 1

**Comment by TorchedSammy** [comment]
gsub returns 2 arguments: the resulting string and the amount of matches
just wrap the return in a () like `return (str:gsub('h', 'ay'))` and that will only take the 1st return value. in the context of where it is used in delta it only takes the 1st but i should maybe change it to be bug prone

but also: can i recommend [promptua](https://github.com/TorchedSammy/Promptua), it would actually be nice to get some more stuff added to that.

**Comment by AlphaTechnolog** [comment]
tysm
