### ISSUE TITLE
[ISSUE] runtime error: invalid memory address

### ISSUE THREAD

**Issue by linuxmobile** [Rosettea/Hilbish#197]
Hi there. I'm trying hilbish again. And i've got the same error when i open the terminal!

```
interface conversion: interface {} is string, not []runtime.Value
runtime error: invalid memory address or nil pointer dereference
```

And another things is.. I want to hide this: 

```
Hilbish 2.0 is a major update! If your config doesn't work
anymore, that will definitely be why! A MOTD, very message, much day.
```

**Comment by linuxmobile** [comment]
```
value is not a continuation
error: error: /usr/share/hilbish/libs/lunacolors/init.lua:104: #3 must be a string, table or function
in function gsub (file [Go])
in function format (file /usr/share/hilbish/libs/lunacolors/init.lua:104)
in function <lua function> (file /usr/share/hilbish/nature/opts/greeting.lua:6)
```

This is another error when i open another terminal

**Comment by TorchedSammy** [comment]
this is a known issue. read #192 
for now you can build the new-emitter branch on your own

> And another things is.. I want to hide this:

set `hilbish.opts.motd` to false

**Comment by linuxmobile** [comment]
> 

This work. Thx for do an amazing job with hilbish, i like it a lot . 

i want to know one more thing. How can i add an alias like this: `pacman -Q | fzf`
If i write this in hilbish, it work, but if i add it as an alias, it say: _| this word don't work_ ...

**Comment by TorchedSammy** [comment]
open a separate issue for it
