### ISSUE TITLE
feat: add command builtins

### ISSUE THREAD

**Issue by TorchedSammy** [Rosettea/Hilbish#199]
hilbish itself doesnt provide a lot of builtins. the sh interpreter does add a few but the common important ones are not there.

on windows, a lot of the commands available on a linux system are not available (for hopefully obvious reasons), so there is no ls or cat, etc. hilbish should implement them in some capacity to have a closer and similar experience on all platforms (mainly windows)

this includes: ls, clear, cat, etc.

**Comment by danitw** [comment]
hi, i can do this?

**Comment by danitw** [comment]
I don't know what the procedure is to collaborate on a project so I'll ask

**Comment by TorchedSammy** [comment]
i really just need suggestions for the commands to add since i already have a branch for the commands (its just called builtins) and if you are gonna pr, do them to the branch

**Comment by danitw** [comment]
ok, i don't have suggestions but i can look

i saw that don't have ls and cat, will i do ok?

**Comment by TorchedSammy** [comment]
sure
