### ISSUE TITLE
[FAQ] How to add alias with | pipe?

### ISSUE THREAD

**Issue by linuxmobile** [Rosettea/Hilbish#201]
Hi, i want to know if there is a way to add commands like: `"pacman -Q | fzf"`. 

When i add this as a normal alias it return:
![image](https://user-images.githubusercontent.com/10554636/186312346-33ae3128-b598-4859-b94f-24b0e1b4345d.png)

I don't know too much about lua. Sorry if i'm a dumb!

**Comment by linuxmobile** [comment]
Oh. Ignore it.

I'll fix adding this: `"sh -c 'pacman -Q | fzf'"`

**Comment by TorchedSammy** [comment]
this was a problem with how hilbish and the sh interpreter work interactively. i just expanded the alias before going to the sh runner now, so it is fixed.

note that this still not work if you want to pipe to/from the alias (that never worked)

**Comment by TorchedSammy** [comment]
fyi before i fixed it you could have aliased to `hilbish.runner.sh "<command here>"` and that would be faster and less overhead

**Comment by linuxmobile** [comment]
> fyi before i fixed it you could have aliased to `hilbish.runner.sh "<command here>"` and that would be faster and less overhead

Amazing!!! I will check it now. Thx u
