### ISSUE TITLE
Using Fennel for configuration and shell

### ISSUE THREAD

**Issue by gasacchi** [Rosettea/Hilbish#204]
Hi, how to configure hilbish with [Fennel](https://fennel-lang.org/) and also using it as shell command?

**Comment by TorchedSammy** [comment]
for using it interactively (the mentioned shell commands) you should look into the runner mode feature via the `doc runner-mode` command. there are some people who have their config in fennel (@Renzix) so you can look as reference when they post it

**Comment by Renzix** [comment]
https://gitlab.com/renzix/Dotfiles/-/tree/master/.config/hilbish I just use fennel for config and shell for shell by including fennel.lua (it has the entire compiler) and doing
```lua
#!/usr/bin/env lua
local fennel = require 'fennel'
fennel.dofile("/home/genzix/.config/hilbish/init.fnl", {compilerEnv = _G})
```

**Comment by gasacchi** [comment]
> for using it interactively (the mentioned shell commands) you should look into the runner mode feature via the `doc runner-mode` command. there are some people who have their config in fennel (@Renzix) so you can look as reference when they post it

i will look into it, thanks 😃 

> https://gitlab.com/renzix/Dotfiles/-/tree/master/.config/hilbish I just use fennel for config and shell for shell by including fennel.lua (it has the entire compiler in a single file which you can download online) and doing
> 
> ```lua
> #!/usr/bin/env lua
> local fennel = require 'fennel'
> fennel.dofile("/home/genzix/.config/hilbish/init.fnl", {compilerEnv = _G})
> ```

getting error:
```bash
error: /usr/share/hilbish/nature/init.lua:31: #1 must be a string
in function getenv (file [Go])
in function __index (file /usr/share/hilbish/nature/init.lua:31)
in function stablenext (file ./fennel.lua)
in function kvmap (file ./fennel.lua:4736)
in function current_global_names (file ./fennel.lua:750)
in function eval_opts (file ./fennel.lua:5089)
in function eval (file ./fennel.lua:5103)
in function <main chunk> (file /home/gasacchi/.config/hilbish/init.lua:7)
An error has occured while loading your config! Falling back to minimal default config.
Hilbish 2.0 is a major update! If your config doesn't work
anymore, that will definitely be why! A MOTD, very message, much day.

Welcome to Hilbish, gasacchi.
The nice lil shell for Lua fanatics!
```

**Comment by TorchedSammy** [comment]
did a simple fix so that should work now

**Comment by TorchedSammy** [comment]
any other error would be due to your fennel config

**Comment by gasacchi** [comment]
yes, try it just now. working perfectly fine thanks for fast response ❤️
