### ISSUE TITLE
Shell locked on command substitution

### ISSUE THREAD

**Issue by leath-dub** [Rosettea/Hilbish#261]
Hilbish version: v2.1.2 (Pansy)

I am not sure if this is a bug or if I am missing something, I am new to hilbish. I assume hilbish does not support the "<(command)" syntax from bash and zsh however when you use it there is no error when you attempt to use it.

e.g: try run this
```sh
ls <(echo hello)
```
on bash or zsh this will just print a path but on hilbish you get a path and the shell locks up (ctrl-d and ctrl-c or any keystroke does nothing)

Edit: after some more investigation, seems like the following works

```sh
$ echo hello | paste - <(echo hello)
hello    hello
```

Which suggests its an issue of not closing the temp file if nobody reads from it ? I haven't looked into the source code so I am just guessing

**Comment by TorchedSammy** [comment]
can you try running on the master branch? otherwise i'll see if updating the sh interpreter package fixes it

**Comment by leath-dub** [comment]
> can you try running on the master branch? otherwise i'll see if updating the sh interpreter package fixes it

same issue on master

**Comment by TorchedSammy** [comment]
can you report the issue to [upstream](https://github.com/mvdan/sh)? i'm sure you'll find the issue is also present on their latest commit by `go run cmd/gosh/main.go`

**Comment by leath-dub** [comment]
> can you report the issue to [upstream](https://github.com/mvdan/sh)? i'm sure you'll find the issue is also present on their latest commit by `go run cmd/gosh/main.go`

Yep it is an issue there. Ill make an issue there.
