### ISSUE TITLE
fix: newline at start of prompt format string produces artifact

### ISSUE THREAD

**Issue by tranzystorekk** [Rosettea/Hilbish#278]
I'm trying to get a multiline prompt that inserts a newline after command output for visual clarity.

With the following prompt config:

```lua
local function doPrompt(fail)
	hilbish.prompt(lunacolors.format(
		'\n{blue}%u {cyan}%d\n' .. (fail and '{red}' or '{green}') .. '∆ '
	))
end
```

Instead of an empty line after command I'm getting a "highlighted" prompt triangle:

![obraz](https://github.com/Rosettea/Hilbish/assets/5671049/9487a137-39a6-4362-ae1e-efdc1b2cb21f)

**Comment by TorchedSammy** [comment]
hilbish outputs that for lines that don't have a newline.

it would probably be better to use the `command.exit` hook:
```lua
bait.catch('command.exit', function()
	print ''
end)
```
