### ISSUE TITLE
Requiring lua modules

### ISSUE THREAD

**Issue by CapedBojji** [Rosettea/Hilbish#279]
is there a way to require other lua files and files from lua rocks

**Comment by TorchedSammy** [comment]
you can add the default lua package paths:
`package.path = package.path .. ';/usr/share/lua/5.4/?.lua;/usr/share/lua/5.4/?/init.lua;/usr/lib64/lua/5.4/?.lua;/usr/lib64/lua/5.4/?/init.lua;'`

and then require `luarocks.loader`, and now you can require luarocks modules.
maybe i can add the lua package.path for the next release.

**Comment by CapedBojji** [comment]
yeah i think that should be added by default thanks
