### ISSUE TITLE
how to use / what to expect / unexpected behavior

### ISSUE THREAD

**Issue by m-faith** [Rosettea/Hilbish#281]
I have `hilbish` installed and working but I'm surprised by:

```
m ~/code/docs ∆ date
Sat Dec 30 12:39:50 PM EST 2023
m ~/code/docs ∆ d
hilbish: d not found
m ~/code/docs ∆ d = date
m ~/code/docs ∆ d
hilbish: d not found
m ~/code/docs ∆ d = date; print(d)
nil
```

...I'm expecting to be able to assign a shell command's output (`date` in this case) to a variable but it doesn't work.

Is it possible to do that? Is there documentation around use of lua/shell syntax?

**Comment by TorchedSammy** [comment]
to get output from a lua command, use [`hilbish.run`](https://rosettea.github.io/Hilbish/docs/api/hilbish/#run)

you can run either lua or shell script interactively, but not both as you're trying to do.

**Comment by m-faith** [comment]
gotcha, thank you!
