### ISSUE TITLE
Defining highlighter doesn't work on master

### ISSUE THREAD

**Issue by jdugan6240** [Rosettea/Hilbish#289]
Since commit [5b8471802175b416b948262178bb5f7b496a7772](https://github.com/Rosettea/Hilbish/commit/5b8471802175b416b948262178bb5f7b496a7772), which merged your line flickering fixes, it appears that defining a highlighter no longer works. I tried the following example from the docs:

```lua
--This code will highlight all double quoted strings in green.
function hilbish.highlighter(line)
   return line:gsub('"%w+"', function(c) return lunacolors.green(c) end)
end
```

Looking at the commit diff, it appears to me that the culprit lies in the changes to the `hilbishLoad` function in `api.go`, where the ability to set `hilbish.highlighter` and `hilbish.hinter` was removed.

**Comment by TorchedSammy** [comment]
The regression was caused by #287

**Comment by jdugan6240** [comment]
Yeah, that did it. Thanks!
