### ISSUE TITLE
Doesn't Build in Go 1.23

### ISSUE THREAD

**Issue by jdugan6240** [Rosettea/Hilbish#326]
Recently, Go 1.23 was released, and with it appear to be some breaking changes that prevent Hilbish from building successfully.

When I try to clone Hilbish and build it, `go get` is able to retrieve the necessary libraries, but `task` is yielding the following output:

```bash
# hilbish
link: github.com/arnodel/golua/runtime: invalid reference to runtime.int64Hash
task: failed to run task "default": exit status 1
```

When modifying Taskfile.yaml to explicitly use a go 1.22 install instead, Hilbish builds successfully.

Given the error message, it seems the issue lies with golua, not Hilbish per se, but since your fork doesn't seem to support issues, I'm posting here instead.

**Comment by TorchedSammy** [comment]
see https://github.com/golang/go/issues/67401
