### ISSUE TITLE
fix: frozen after setting alias with same name as command

### ISSUE THREAD

**Issue by TorchedSammy** [Rosettea/Hilbish#67]
example: `alias("ls", "ls -lh")`
this shouldnt be happening :|

**Comment by TorchedSammy** [comment]
sure, go ahead

**Comment by ratogabriel** [comment]
Hi, I opened the PR: https://github.com/Rosettea/Hilbish/pull/73 if you could take a look :smile:

**Comment by TorchedSammy** [comment]
resolved
